### PR TITLE
update to axum v0.7

### PR DESCRIPTION
**Pull request by utterstep**
Hi! First of all, thank you for your lib!

This PR updates the axum dependency to v0.7 – what do you think about it? 0.7 was released [a bit more than a year ago](https://github.com/tokio-rs/axum/releases/tag/axum-v0.7.0) and the there is already RC for 0.8.

### CODE REVIEW

**Comment by cmackenzie1** [comment]
Thanks @utterstep, this looks great. I think we need to bump `hyper` as well to `1.0` and it should be good to merge!

**Comment by utterstep** [comment]
Thank you for the feedback! I updated the example to use [`axum::serve`](https://docs.rs/axum/latest/axum/fn.serve.html) to keep it simple, is that OK?

It can be found in [c92620a](https://github.com/cmackenzie1/axum-jwt-auth/pull/4/commits/c92620a8484f479039e7b766c7b2a63a9e5c0c4f)

I also noticed that some of the dependencies were used only indirectly, by other dependencies (like `hyper`, `tower`, `serde_json`). I took the liberty of removing them in the separate commit. Also, I moved `chrono` to dev-dependencies as it is only the example code that depends on it, and not the lib.
This was done in the [7873c88](https://github.com/cmackenzie1/axum-jwt-auth/pull/4/commits/7873c88d8966e97807e0cced99118219b2646e56).

And lastly I updated `reqwest` and `jsonwebtoken` to the latest versions also in [bfa0b6d](https://github.com/cmackenzie1/axum-jwt-auth/pull/4/commits/bfa0b6db4c6e80650068cd2cca6d4f2456759645).

I understand that last two commits are out of the scope of the PR so in case you'd like to keep to the original purpose – I have no problems reverting any of them or both.

**Review by cmackenzie1 — APPROVED** [review]

**Comment by cmackenzie1** [comment]
Looks great, thanks @utterstep !

**Comment by cmackenzie1** [comment]
Version 0.2.0 has been published with these changes!

https://github.com/cmackenzie1/axum-jwt-auth/releases/tag/v0.2.0
https://crates.io/crates/axum-jwt-auth/0.2.0
https://docs.rs/crate/axum-jwt-auth/0.2.0

**Pull request merged**
